################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=DP-1, 2560x1440@59.95, 0x0, 1
monitor=HDMI-A-1, 1920x1080@60, -1080x-150, 1, transform, 3
monitor=eDP-1, disabled
