#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

#Start polkit agent (elevated privelages)
exec-once = systemctl --user start hyprpolkitagent
#Star Kanshi - Setup profile manager (laptop/dock)
exec-once = kanshi
#Start hypridle - idle daemon - ex. turns on hyprlock after some time
exec-once = hypridle
#Start hyprlock - start screen lock tool
exec-once = hyprlock --config ~/.config/hypr/hyprlock/hyprlock.conf --immediate
#Start network-manager applet
exec-once = nm-applet &
#Start player daemon - tool that tracks media sources (youtube/spotify)
exec-once = playerctld daemon
#Start toolbar and wallpaper tools
exec-once = waybar & hyprpaper
#Start openrgb - keyboard backlight tool
exec-once = openrgb --device 0 --mode direct --color 26EF14
#Start dunst - notification daemon
exec-once = dunst

#Start cliphist for wl-clipboard
# exec-once = wl-paste --type text --watch cliphist store # Stores only text data
# exec-once = wl-paste --type image --watch cliphist store # Stores only image data
