preload = /home/d3athw1sh/dotfiles/Images/wallpaper.jpg

wallpaper {
    monitor = DP-1
    path = ~/dotfiles/Images/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/dotfiles/Images/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/dotfiles/Images/wallpaper.jpg
    fit_mode = cover
}


splash = false
ipc = off