#Setting up font family
font_family JetBrainsMono Nerd Font

# Make the cursor shape a beam
shell_integration no-cursor
cursor_shape block

# Padding
window_padding_width 15

# Scroll back up to 3000 lines.
scrollback_lines 3000

#Default font size.
font_size 11

# Just a keybind to change font size to your liking, it's CTRL + scroll wheel up or down.
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Background opacity, set to 0 if you want blur/transparency.
# Blur works with hyprland, or sway-fx as a drop-in replacement for sway.
background_opacity 0.85

cursor #8ff586

background #051a05
foreground #dcf9d9

selection_foreground #0d2514
selection_background #8ff586

#BLACK
color0 #dcf9d9
color8 #dcf9d9
#RED
color1 #ff4b6b
color9 #ff4b6b
#GREEN
color2 #8ff586
color10 #8ff586
#YELLOW
color3 #dbf227
color11 #dbf227
#BLUE
color4 #4fa6ed
color12 #4fa6ed
#MAGENTA
color5 #ff2b83
color13 #ff2b83
#CYAN
color6 #8ff586
color14 #6cbc67
#WHITE
color7 #ba45b1
color15 #ba45b1


# # START_AUTOGENERATED_TAB_STYLE
# active_tab_foreground   #eeeeee
# active_tab_background   #084fb0
# inactive_tab_foreground #8ff586
# inactive_tab_background #10202d
# # END_AUTOGENERATED_TAB_STYLE